JsonLitz/chalk_up

app/assets/javascripts/users.coffee, app/assets/stylesheets/users.scss, app/controllers/users_controller.rb, app/helpers/users_helper.rb, config/routes.rb
Added empty methods in users.controller and created db
=> add routes and controllers

app/assets/javascripts/climbs.coffee, app/assets/stylesheets/climbs.scss, app/controllers/climbs_controller.rb, app/helpers/climbs_helper.rb, app/models/climb.rb, app/models/comment.rb, app/models/user.rb, db/migrate/20160825235347_create_users.rb, db/migrate/20160826000231_create_comments.rb, db/migrate/20160826000825_create_climbs.rb, db/migrate/20160826001150_add_more_fields_to_climbs_model.rb, db/schema.rb
added fields for comments and climbs models. changes are reflected in schema
=> add climb and comments models

app/controllers/sessions_controller.rb, app/helpers/sessions_helper.rb, config/routes.rb
created sessions controller with the base 3 methods: new, create, destroy
=> set up sessions controller with methods

app/controllers/users_controller.rb, app/views/climbs/index.html.erb, app/views/users/index.html, app/views/users/new.html.erb, config/routes.rb, db/migrate/20160826181215_create_password_field_for_user.rb, db/schema.rb
Added password field and created a view for new users
=> Password field creation

app/assets/stylesheets/application.css, app/controllers/climbs_controller.rb, app/views/layouts/application.html.erb
=> initial navbar up

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/controllers/sessions_controller.rb, app/controllers/users_controller.rb, app/models/user.rb, app/views/climbs/index.html.erb, app/views/users/new.html.erb
1. add confirm method to user model
2. add bcrypt gem
3. password_digest only in schema and migration files for users (bcrypt)
4. all other instances of password have been set to :password
Note : user must be created through the browser form (not console create)!
=> User login fix

app/controllers/users_controller.rb, app/views/users/new.html.erb, app/views/users/show.html.erb
Added user image and button path for new location on user profile show page
=> User Show page

app/controllers/application_controller.rb, app/controllers/climbs_controller.rb, app/helpers/application_helper.rb, app/views/layouts/application.html.erb
Sexy navbar link logic to rewrite routes depending on user login
=> Login nav link logic

app/controllers/application_controller.rb, app/controllers/climbs_controller.rb, app/helpers/application_helper.rb, app/views/layouts/_header.html.erb, app/views/layouts/application.html.erb, app/views/users/show.html.erb
Added new nav bar and merged with logic to dynamically create buttons for navigation depending on view.
=> Header partial2

app/models/climb.rb, app/models/user.rb
validation for username and password in user model and image url validation
=> password validation

Gemfile, app/assets/stylesheets/climbs.scss, app/controllers/climbs_controller.rb, app/helpers/climbs_helper.rb, app/views/climbs/_climb.html.erb, app/views/climbs/edit.html.erb, app/views/climbs/new.html.erb, app/views/climbs/show.html.erb, config/routes.rb, db/migrate/20160828181342_add_default_value_to_gear_array.rb, db/schema.rb
1. create show.html.erb view for climbs
2. create and render _climb partial in show view
3. style partial
=> Climb show partial

app/assets/stylesheets/climbs.scss, app/models/climb.rb, app/views/climbs/index.html.erb, app/views/climbs/new.html.erb
added necessary fields and add button on map view page
=> Climb loc form

app/controllers/users_controller.rb, app/views/users/_form.html.erb, app/views/users/new.html.erb
- error handling in user new form
=> Error handling

app/assets/stylesheets/application.css, app/assets/stylesheets/climbs.scss, app/views/climbs/_form.html.erb, app/views/climbs/index.html.erb, app/views/sessions/new.html.erb, app/views/users/new.html.erb
=> Form border

app/views/climbs/_climb.html.erb
add border for climb show partial
=> add climb show partial borders

app/assets/javascripts/climbs.js, app/controllers/climbs_controller.rb, app/views/climbs/index.html.erb
multi-marker rendering on google map; centers on current location
=> Geo loc multi markers

app/assets/stylesheets/application.css, app/views/climbs/_climb.html.erb, app/views/climbs/index.html.erb
Rendered climb partials onto index page and added some basic bordering
=> render climb partials on index page

app/controllers/climbs_controller.rb, app/controllers/comments_controller.rb, app/helpers/sessions_helper.rb, app/models/climb.rb, app/views/climbs/_climb.html.erb, config/routes.rb
- change routes for comments to remove aliases for post and make paths match/be shallow
- make a href's into link_to's on climbs partial
=> comments routes & climb partial mini edits

app/helpers/application_helper.rb
fixed the navbar link generator
=> Navbar link fix

app/views/climbs/_form.html.erb
form autofills longitude and lat for new climb spot
-still need to add the hidden attr to these form items
- need to build a button that toggles the hidden fields to visible and once visible it sets the values back to nil.
=> Autofill geo loc

app/assets/stylesheets/climbs.scss, app/models/climb.rb, app/views/climbs/_climb.html.erb, app/views/climbs/_form.html.erb, app/views/climbs/index.html.erb
- replace climb form 'type' placeholder with 'style
- add panel divs to climb partial for styling
=> Style climb partial

app/controllers/climbs_controller.rb, app/views/climbs/_form.html.erb, app/views/climbs/edit.html.erb, db/migrate/20160830230522_create_join_table_climbs_users.rb, db/migrate/20160831004319_drop_table.rb
- fix climb edit form to match styling of climb new
- create and delete join table because it isn't useful
=> fixing forms

app/controllers/users_controller.rb, app/views/users/show.html.erb
- add checkin climb name to user profile with timestamp
=> More fixes

app/views/climbs/_form.html.erb, app/views/climbs/index.html.erb, db/schema.rb
=> styling changes
